### ISSUE TITLE
Add shortcut for Archive.org

### ISSUE THREAD

**Issue by MartijnOud** [sanderheilbron/seo-shortcuts#11]
Shortcut to open current page in the [Wayback machine](http://web.archive.org/).

Example: http://web.archive.org/web/*/https://www.sanderheilbron.nl
Syntax: `https://web.archive.org/web/*/'+document.location.href`
Possible shortcut: `archive`, `wbm`

**Comment by sanderheilbron** [comment]
Thanks, but is already available via command ```wbm``` :)

**Comment by MartijnOud** [comment]
Haha my bad. That command has been available for a while but I apparently forgot and didn't check thoroughly enough 😅
