### ISSUE TITLE
Add shortcut for BuiltWith

### ISSUE THREAD

**Issue by MartijnOud** [sanderheilbron/seo-shortcuts#8]
Shortcut to open current page in [BuiltWith](https://builtwith.com/).

Example: https://builtwith.com/?https://github.com/
Syntax: `"https://builtwith.com/?" + document.location.href`
Possible shortcut: `bw`

**Comment by sanderheilbron** [comment]
Thanks @MartijnOud, I will add this shortcut to the extension.
